/**
 * Click instrumentation (issue #399, part of the #160 analytics PRD).
 *
 * One delegated listener pair on `document` resolves what was clicked and hands
 * the result to `window.NycAnalytics.track()`. Delegation is required rather
 * than stylistic: `partials-loader.js` injects the header and footer with
 * `insertAdjacentHTML` after load, and tiles, slides and calendar bars are all
 * generated by JS, so a listener bound at DOMContentLoaded would miss them.
 *
 * ---------------------------------------------------------------------------
 * THIS IS NOT A REDESIGN COMPONENT — DO NOT ADD A FLAG GATE.
 * ---------------------------------------------------------------------------
 * Same inversion of CLAUDE.md's house rule as `consent.js` and `analytics.js`:
 * the redesign flag is OFF in every environment and the redesign is parked
 * (#403), so a gate here would leave the site asking for a consent decision and
 * then measuring nothing at all.
 *
 * ---------------------------------------------------------------------------
 * THE THING THIS FILE EXISTS TO GET RIGHT
 * ---------------------------------------------------------------------------
 * The homepage carousel advances on a 5s timer (`carousel.js:179`). Every rule
 * below hangs off a real interaction — a click, or the Enter key on something
 * that navigates — and never off a render. Instrumenting the render path would
 * log carousel engagement on every homepage visit from visitors who never
 * touched it, corrupting the one report this milestone exists to produce.
 * `tests/e2e/analytics-events.spec.js` sits on that.
 *
 * CAPTURE PHASE, DELIBERATELY. Calendar bars, "+N more" links and carousel dots
 * all call `stopPropagation()` in their own handlers, so a bubble-phase
 * listener on `document` would never see a single calendar click. Capture runs
 * before the target's own handler, which also means the DOM is read *before*
 * those handlers mutate it — see `menu_open` and `calendar_month_change`.
 *
 * NO FREE TEXT, EVER. `link_text` is the site's own fixed navigation labels,
 * `entry_id` is a Sanity document id. Nothing a visitor typed reaches a
 * parameter, and no parameter carries a raw path or query string.
 */
(function createAnalyticsEventsModule(globalScope) {
  'use strict';

  /**
   * The module walks the tree with these two helpers rather than
   * `Element.closest`, so the resolution rules can be unit-tested in plain Node
   * against plain objects. They are the part of this issue most likely to be
   * got wrong and the part a browser test can only reach one click at a time.
   */
  function closestByClass(node, className) {
    let current = node;
    while (current) {
      if (current.classList && current.classList.contains(className)) {
        return current;
      }
      current = current.parentNode;
    }
    return null;
  }

  function closestByTag(node, tagName) {
    const wanted = tagName.toUpperCase();
    let current = node;
    while (current) {
      if (current.tagName === wanted) {
        return current;
      }
      current = current.parentNode;
    }
    return null;
  }

  function closestWithAttribute(node, attribute) {
    let current = node;
    while (current) {
      if (typeof current.getAttribute === 'function' && current.getAttribute(attribute) !== null) {
        return current;
      }
      current = current.parentNode;
    }
    return null;
  }

  function attribute(node, name) {
    return node && typeof node.getAttribute === 'function' ? node.getAttribute(name) : null;
  }

  const SOCIAL_HOSTS = [
    { platform: 'instagram', pattern: /(^|\.)instagram\.com$/i },
    { platform: 'tiktok', pattern: /(^|\.)tiktok\.com$/i },
    { platform: 'substack', pattern: /(^|\.)substack\.com$/i },
  ];

  /**
   * Matched on the host, never on the whole href: a path containing the word
   * "instagram" on some unrelated domain is not an Instagram click.
   */
  function platformFor(href) {
    if (typeof href !== 'string' || href === '') {
      return null;
    }
    if (href.toLowerCase().startsWith('mailto:')) {
      return 'email';
    }
    const host = destinationDomainFor(href);
    if (!host) {
      return null;
    }
    const match = SOCIAL_HOSTS.find((entry) => entry.pattern.test(host));
    return match ? match.platform : null;
  }

  /** The host alone — never the path or query, which is where PII would hide. */
  function destinationDomainFor(href) {
    if (typeof href !== 'string' || href === '') {
      return null;
    }
    try {
      return new URL(href).hostname || null;
    } catch {
      return null;
    }
  }

  function entryIdFromHref(href) {
    if (typeof href !== 'string' || href === '') {
      return null;
    }
    const match = /[?&]id=([^&#]+)/.exec(href);
    return match ? decodeURIComponent(match[1]) : null;
  }

  function contentTypeFromHref(href) {
    if (typeof href !== 'string') {
      return null;
    }
    if (href.includes('date-idea')) {
      return 'date_idea';
    }
    if (href.includes('pop-up')) {
      return 'popup';
    }
    return null;
  }

  /**
   * Whole months between the month on screen and the month it is now, signed.
   * Answers "does anyone browse beyond this month" without a date ever leaving
   * the site as free text.
   */
  function monthsFromCurrent(monthValue, now) {
    if (typeof monthValue !== 'string' || !/^\d{4}-\d{2}$/.test(monthValue)) {
      return null;
    }
    const [year, month] = monthValue.split('-').map(Number);
    if (!Number.isFinite(year) || month < 1 || month > 12) {
      return null;
    }
    const reference = now instanceof Date && !Number.isNaN(now.getTime()) ? now : new Date();
    return (year - reference.getFullYear()) * 12 + (month - 1 - reference.getMonth());
  }

  /** Site-authored labels only, collapsed because the markup wraps them. */
  function labelFor(node) {
    const text = node && typeof node.textContent === 'string' ? node.textContent : '';
    return text.replace(/\s+/g, ' ').trim().slice(0, 100);
  }

  /** Index among the siblings that are tiles too — the list position (§5). */
  function positionAmongTiles(node) {
    const parent = node.parentNode;
    if (!parent || !parent.children) {
      return null;
    }
    const tiles = Array.prototype.filter.call(
      parent.children,
      (child) => child.classList && child.classList.contains('popup-tile'),
    );
    const index = Array.prototype.indexOf.call(tiles, node);
    return index === -1 ? null : index;
  }

  function navLocationFor(node) {
    if (closestByClass(node, 'collapsible-menu')) {
      return 'header_mobile';
    }
    if (closestByClass(node, 'site-header')) {
      return 'header';
    }
    if (closestByClass(node, 'site-footer')) {
      return 'footer';
    }
    if (closestByClass(node, 'home-menu')) {
      return 'home_quicknav';
    }
    return null;
  }

  /**
   * `social_click`'s placement vocabulary is the three values in §5. The
   * collapsible menu is part of the header, so it reports `header`: the
   * mobile-versus-desktop question is answered by `nav_click`'s own
   * `nav_location`, and splitting it across two events would answer it twice
   * and worse.
   */
  function socialLocationFor(node) {
    if (closestByClass(node, 'site-header')) {
      return 'header';
    }
    if (closestByClass(node, 'site-footer')) {
      return 'footer';
    }
    return 'home';
  }

  function contentOpen(params) {
    return { name: 'content_open', params };
  }

  /**
   * The single resolution rule set. Order matters and is deliberate: the
   * specific components come before the generic link handling, or a date ideas
   * tile (a real anchor) would resolve as navigation.
   */
  function resolveClick(target, context) {
    if (!target) {
      return null;
    }
    const ctx = context || {};

    // Not tracked, on purpose. A dot changes slide and opens nothing, and no
    // event in §5 covers it; inventing a ninth name here would be permanent,
    // because GA4 never renames historical data.
    if (closestByClass(target, 'carousel-dot')) {
      return null;
    }

    // Counting a privacy control as navigation would be its own small
    // dishonesty, and the footer button carries the footer link class.
    if (closestByClass(target, 'nyc-consent') || closestWithAttribute(target, 'data-consent-settings')) {
      return null;
    }

    const monthButton = closestByClass(target, 'calendar-header__prev-month')
      ? 'prev'
      : (closestByClass(target, 'calendar-header__next-month') ? 'next' : null);
    if (monthButton) {
      const header = closestByClass(target, 'calendar-header');
      const displayed = monthsFromCurrent(attribute(header, 'data-analytics-month'), ctx.now);
      const params = { direction: monthButton };
      if (displayed !== null) {
        // Capture phase, so the header still names the month being left. The
        // month that matters is the one this click lands on.
        params.months_from_current = displayed + (monthButton === 'next' ? 1 : -1);
      }
      return { name: 'calendar_month_change', params };
    }

    const toggle = closestByClass(target, 'menu-toggle');
    if (toggle) {
      // "toggle" conflates opening and closing (§5), so only the open counts.
      // Capture runs before the class is flipped: closed now means about to open.
      const container = closestByClass(toggle, 'header-container') || toggle.parentNode;
      const menu = container && container.children
        ? Array.prototype.find.call(container.children, (child) => child.classList
          && child.classList.contains('collapsible-menu'))
        : null;
      if (menu && menu.classList.contains('open')) {
        return null;
      }
      return { name: 'menu_open', params: {} };
    }

    const bar = closestByClass(target, 'calendar-popup-bar');
    if (bar) {
      // A bar sits on a date grid rather than in an ordered list, so `position`
      // has no meaning here and an invented ordinal would be worse than none.
      //
      // The document id wins over `data-event-id`: that attribute is the
      // per-occurrence key the segment highlighting uses, so a multi-day
      // pop-up carries several and would count as several entries in GA4.
      return contentOpen({
        content_type: 'popup',
        surface: 'calendar',
        entry_id: attribute(bar, 'data-analytics-id') || attribute(bar, 'data-event-id'),
      });
    }

    const tile = closestByClass(target, 'popup-tile');
    if (tile) {
      const href = attribute(tile, 'href');
      const params = {
        content_type: attribute(tile, 'data-analytics-type') || contentTypeFromHref(href) || 'popup',
        // The "+N more" modal reuses the pop-ups grid markup, so the day grid is
        // the only thing separating a calendar discovery from a list one.
        surface: closestByClass(tile, 'day-popups-grid') ? 'calendar_more' : 'list',
        entry_id: attribute(tile, 'data-analytics-id') || entryIdFromHref(href),
      };
      const position = positionAmongTiles(tile);
      if (position !== null) {
        params.position = position;
      }
      return contentOpen(params);
    }

    const slide = closestByClass(target, 'carousel-slide') || closestByClass(target, 'carousel-title');
    if (slide) {
      const params = {
        content_type: 'popup',
        surface: 'carousel',
        entry_id: attribute(slide, 'data-analytics-id'),
      };
      const position = Number(attribute(slide, 'data-analytics-position'));
      if (Number.isInteger(position)) {
        params.position = position;
      }
      return contentOpen(params);
    }

    const link = closestByTag(target, 'A');

    if (link && attribute(link, 'id') === 'popupExternalLink') {
      const href = attribute(link, 'href');
      return {
        name: 'outbound_click',
        params: {
          content_type: contentTypeFromHref(ctx.pathname || '') || 'popup',
          entry_id: entryIdFromHref(ctx.search),
          destination_domain: destinationDomainFor(href),
        },
      };
    }

    // Both the single link and the per-day links a multi-day pop-up renders.
    if (link && closestByClass(link, 'modal-link') && closestByClass(link, 'popup-detail')) {
      return { name: 'content_save', params: { entry_id: entryIdFromHref(ctx.search) } };
    }

    if (link) {
      const href = attribute(link, 'href');

      // The header's Substack entry is both a nav link and a social link. It is
      // counted as social so that "which placement earns social clicks" has one
      // answer per placement rather than one split across two events.
      const platform = platformFor(href);
      if (platform) {
        return { name: 'social_click', params: { platform, location: socialLocationFor(link) } };
      }

      const navLocation = navLocationFor(link);
      if (navLocation) {
        return {
          name: 'nav_click',
          params: { nav_location: navLocation, link_text: labelFor(link), destination: href },
        };
      }
    }

    return null;
  }

  /** Enter on these navigates; they are not buttons, so no click follows. */
  function isKeyboardActivable(target) {
    return Boolean(closestByClass(target, 'carousel-slide') || closestByClass(target, 'calendar-popup-bar'));
  }

  function createEvents(options) {
    const settings = options || {};
    const doc = settings.document;
    const analytics = settings.analytics;
    const locationLike = settings.location || {};

    function context() {
      return {
        origin: locationLike.origin,
        pathname: locationLike.pathname,
        search: locationLike.search,
        now: new Date(),
      };
    }

    function send(target) {
      if (!analytics || typeof analytics.track !== 'function') {
        return;
      }
      const resolved = resolveClick(target, context());
      if (resolved) {
        // track() refuses on anything but a stored grant, so the consent gate
        // stays in one file. Nothing here decides whether to send.
        analytics.track(resolved.name, resolved.params);
      }
    }

    function start() {
      if (!doc || typeof doc.addEventListener !== 'function') {
        return;
      }
      // Capture, so a stopPropagation() in a component's own handler — every
      // calendar bar and "+N more" link has one — cannot hide the click.
      doc.addEventListener('click', (event) => send(event && event.target), { capture: true });
      doc.addEventListener('keydown', (event) => {
        if (!event || (event.key !== 'Enter' && event.key !== ' ')) {
          return;
        }
        // A real <a> or <button> fires its own click on Enter; counting the
        // keydown as well would double every keyboard navigation.
        if (!isKeyboardActivable(event.target)) {
          return;
        }
        send(event.target);
      }, { capture: true });
    }

    return { start };
  }

  const api = {
    resolveClick,
    platformFor,
    destinationDomainFor,
    entryIdFromHref,
    contentTypeFromHref,
    monthsFromCurrent,
    labelFor,
    createEvents,
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  }

  if (typeof window !== 'undefined') {
    window.nycAnalyticsEventsModule = api;
    window.NycAnalyticsEvents = createEvents({
      document: window.document,
      analytics: window.NycAnalytics,
      location: window.location,
    });
    window.NycAnalyticsEvents.start();
  }
}(typeof globalThis !== 'undefined' ? globalThis : this));
